# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Use node.js
      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Install dependencies
      - name: Install Packages
        run: yarn install
        
      # Build
      - name: Build page
        run: yarn build
      
      # Transfer
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          # Path to the local folder you want to copy.
          local: ./build/
          # Path on the remote server to copy to.
          remote: ${{ secrets.FTP_FOLDER }}
          # Hostname or IP address of the server.
          host: janka.la
          # Username for authentication.
          username: ${{ secrets.FTP_USER }}
          # Port number of the server.
          port: 22
          # Password for password-based user authentication.
          password: ${{ secrets.FTP_PASSWORD }}
